name: Deploy Terraform and Frontend

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write   # required for OIDC
  contents: read    # required for actions/checkout

jobs:
  Packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Package backend code
        run: ./package_code.sh

      - name: Upload backend packages to S3
        run: |
          aws s3 cp lambda_package.zip s3://${{ secrets.BUCKET_NAME }}/
          aws s3 cp dependencies.zip s3://${{ secrets.BUCKET_NAME }}/

